# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Secoolioo.ClipboardManager
PackageVersion: 0.10.2
InstallerType: portable
MinimumOSVersion: 10.0.19041.0
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Secoolioo/clipboard-manager/releases/download/v0.10.2/ClipboardManager.exe
  InstallerSha256: 45FA476A2562BA2664AB3DB1CB996404634045E128D88B59B028DBC804BCC33E
- Architecture: arm64
  InstallerUrl: https://github.com/Secoolioo/clipboard-manager/releases/download/v0.10.2/ClipboardManager-arm64.exe
  InstallerSha256: 7BECB397698C84E2F46FB891EA6D6F7EE3E6943BF8DB2EBBBD8E44A795050AF7
ManifestType: installer
ManifestVersion: 1.12.0
